feature/create-card
trikripp/product-preview-card pull request #1
Opened 2023-04-25 16:09 UTC by trikripp

2023-04-25 16:18 UTC, millerarocha requested changes

2023-04-25 16:18 UTC, millerarocha commented on style.css
Please add a height property to the body, must be 100%

2023-04-25 16:34 UTC, trikripp commented on style.css
Done!!

2023-04-25 17:46 UTC, millerarocha requested changes

2023-04-25 17:46 UTC, millerarocha commented on style.css
Don´t forget to set the universal styles
```suggestion
*{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

```

2023-04-25 17:46 UTC, millerarocha commented on style.css
> +    height: 100%;
Please use 100vh instead of 100%

2023-04-25 18:14 UTC, trikripp commented on style.css
Done

2023-04-25 18:15 UTC, trikripp commented on style.css
> +    height: 100%;
Done

2023-04-25 21:30 UTC, millerarocha requested changes

2023-04-25 21:30 UTC, millerarocha commented on index.html
> +                    <button><svg width="15" height="16" xmlns="http://www.w3.org/2000/svg"><path d="M14.383 10.388a2.397 2.397 0 0 0-1.518-2.222l1.494-5.593a.8.8 0 0 0-.144-.695.8.8 0 0 0-.631-.28H2.
Please try using, this could be confusing for future developers.
```suggestion
<img src = "image.svg" alt="Image description"/>
```

2023-04-25 21:30 UTC, millerarocha commented on style.css
> +
if you are not using styles for that, please don't let empty css rules

2023-04-25 21:30 UTC, millerarocha commented on index.html
> +                <div class="info-f">
please provide a more explainable name for classes, could be info-footer. Also this div can be deleted.

2023-04-25 21:30 UTC, millerarocha commented on index.html
> +            <footer>
Add the info-footer class here and delete the div, that is reductant

2023-04-25 21:30 UTC, millerarocha commented on style.css
> +    font-weight: 200;
please consider adding line-height property, try with different values to match design.

2023-04-25 21:30 UTC, millerarocha commented on index.html
> +                    <h4>$169.99</h3>
change h4 tag for span tag

2023-04-25 21:30 UTC, millerarocha commented on index.html
> +                    <h4>$169.99</h3>
check that in design this value is located on top, not on bottom

2023-04-25 22:51 UTC, trikripp commented on index.html
> +                    <button><svg width="15" height="16" xmlns="http://www.w3.org/2000/svg"><path d="M14.383 10.388a2.397 2.397 0 0 0-1.518-2.222l1.494-5.593a.8.8 0 0 0-.144-.695.8.8 0 0 0-.631-.28H2.
Done

2023-04-25 22:52 UTC, trikripp commented on style.css
> +
okey

2023-04-25 23:16 UTC, trikripp commented on style.css
> +    font-weight: 200;
okey

2023-04-25 23:17 UTC, trikripp commented on index.html
> +                    <h4>$169.99</h3>
resolved

2023-04-25 23:18 UTC, trikripp commented on index.html
> +                    <h4>$169.99</h3>
ready

2023-04-27 18:20 UTC, millerarocha approved these changes

2023-04-27 18:21 UTC, merged